[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hades-em"
version = "1.0.0"
description = "High-throughput Analysis for the Design of Energetic Systems"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    {name = "Joshua T. Harle"}
]
license = {text = "MIT"}

dependencies = [
    "ase>=3.26",
    "joblib",
    "mace-torch>=0.3.14",
    "numpy",
    "pandas",
    "rdkit>=2025.3.6",
    "scikit-learn",
    "torch",
    "tqdm",
]

[project.scripts]
hades = "hades.cli:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
hades = [
    "data/*.csv",
    "data/*.pkl",
]
